### PR TITLE
crowbar page update with fresh content

### PR DESCRIPTION
**Pull request by sidthe**
full page update + 2 videos introducing crowbar

### CODE REVIEW

**Comment by tboerger** [comment]
:-1: as the entire jekyll functionality gets dropped.

**Comment by sidthe** [comment]
@tboerger yes, I though about it and either I shall spend time integrating that. But then it looks to me presence of the jekyll has not helped in any way to speed up neither the page development, nor adding more content. As such - as it does not bring any practical benefit - I consider this overhead.

I am opened however for you to integrate this with jekyll workflow if you believe it adds any value.

**Comment by rsalevsky** [comment]
Is there somewhere a preview available?

**Comment by sidthe** [comment]
@rsalevsky http://sidthe.github.io/crowbar-page/

**Comment by rsalevsky** [comment]
This page is definitely better and more useful as the old crowbar website. But I see also some problems, for example you introduce a logo. Do we really want to use this as our logo or is this just a placeholder? I would like to see that Ken makes finally a logo which we can use everywhere. I definitely see a use for this for the next summit. Beside this I think it would be nice when we keep the gitter link.

I don't care much about the jekyll as long as it is maintainable.

**Comment by jsuchome** [comment]
I'm not UI expert, so I won't dare to give +1 here, but in general I think it's better to have nice page (as a replacement for horrible one) now, than the perfect one in months.

**Comment by sidthe** [comment]
@rsalevsky its not a logo, its just a glyphicon that made most sense. I'd love to have a logo. We can ask Ken to support with that.
In fact there are additional things that need some fixes, mainly related to responsive behavior and size of media.

So I'd say, let's push this in, and once it is up, I'll ask Ken to add the logo and add the fixes I know it needs

**Comment by MaximilianMeister** [comment]
why don't we just put it in the next sprint? I would really like to see Ken involved, as his team has been doing the design for the websites of other products already.

and why pushing it now, to change it a week later? are we in a hurry?

**Comment by sidthe** [comment]
@MaximilianMeister depends what we call hurry :)) considering when the last update that has been done to the page, it looks like we are definitely not in a hurry :))

Now, Ken might or might not have time in the sprint. Github is there for collaboration. What is the point of time boxing the work? If Ken can support us later - he will do it at his comfort and make a pull request when he is done with an enhanced proposal.

@kwwii would the above work for you?

**Comment by tboerger** [comment]
Still a :-1: from my side. Just because you don't see a benefit in it is not a real argumentation against it. Every web developer knows the benefits to have a proper asset handling including precompiling. Beside that is jekyll a standard tool for github websites.

And on top of that I'm still not happy with just copying a theme for a serious opensource project backed by a company like SUSE.

**Comment by tboerger** [comment]
And as an addition... Jekyll opens also the door to provide even blogging functionality where we can put even more interesting content like embedding the blog post from @aspiers instead of linking to his own blog.

**Comment by sidthe** [comment]
@tboerger I am not denying the benefit of jekyll as such, I am saying that in our particular case this is overhead that did not help. It did not help for a basic page - and we are certainly not even close to get the blogging running. As every web developer also knows putting a site together makes sense if people make use of it.

Regarding the theme. Under the circumstances you can say the same of Bootstrap3 or whatever other library you use. In the end, when you simplify your life with a Ruby Gem, you're reusing someones work. A theme is nothing else then a series of enhancements on top of base bootstrap CS+JS
As such - I appreciate the excuses, but they don't work for me. I would want something more substantial. And substantial for me is not philosophical.

I am also more then happy to have you do it better and put it online - ideally still in the next couple of weeks so we are all prepared before Austin.

**Comment by tboerger** [comment]
So without Jekyll I will be entirely out of the website. I won't work on it anymore without it, that's from my side.

Comparing a theme with frameworks is IMHO a little bit weak compare. And if that is not an argumentation for you let's take it to the next parts. The website is messed up for mobile devices and also behaves differently on smaller resolutions. Just resize your browser window and you will see it.

**Comment by sidthe** [comment]
@tboerger "The website is messed up for mobile devices and also behaves differently on smaller resolutions. Just resize your browser window and you will see it."
This is true. This are exactly the fixes I need some help with as I can't get the behavior consistent across non-standard layouts. I'd appreciate some guidance here.

**Comment by kwwii** [comment]
This gets a +1 from me for the following reason: It is a good step in the right direction. Merging this pull request gets the ball rolling on revamping the site with a good idea of the intended direction. My team can definitely help with this in the coming weeks.

**Comment by sidthe** [comment]
thanks @kwwii let's go from here and next week let's catch up and have a plan for further updates

@tboerger after a quick chat with @kwwii it looks like this behavior at non-standard aspect ratios is a side effect of parallax implementation and is quite hard to get right. Machinery seems to have the same problem with their website.

**Comment by rsimai** [comment]
I see it's already merged, probably I'm late. I support going forward as it's a good start and looks more appealing than before. Have you however checked if we can use the logos from OpenStack, Ceph and Cloud Foundry this way? The latter btw. seems not the right one.

**Comment by aspiers** [comment]
Also, I'm not convinced there's any good reason to use a Cloud Foundry logo on this website as it has nothing to do with Crowbar AFAIK.

**Comment by MaximilianMeister** [comment]
@sidthe I know that this could have delayed it further but usually we wait for at least 2 +1's before merging something. That gives others the chance to have a look as well and helps to find issues beforehand

**Comment by tboerger** [comment]
Ok, i absolutely dislike this behavior! And I will reject every further work on it as there had been no respect to my -1 and my argumentation to keep Jekyll. This behavior is really discouraging.

**Comment by tboerger** [comment]
> @sidthe I know that this could have delayed it further but usually we wait for at least 2 +1's before merging something. That gives others the chance to have a look as well and helps to find issues beforehand

And at least if there is a :-1: it's simply blocked. But as this comes from me it doesn't matter...

**Comment by sidthe** [comment]
thanks for your comments guys.
I can understand why @tboerger you might find it frustrating for me going over your -1, and I can relate to this - but from a completely different view point.

As the first step is done, and I will make sure to have Ken onboard to help us further refine it, I encourage all to focus your efforts on taking actions that actually make things happen. I would be happy to have Jekyll reverted and integrated with the UI if anyone is willing to spend some time on it. If not, then any discussion about it is useless. 

And I think it will only be fair if @tboerger you help with that. I did spend my personal time to address your concern from last week that the principal problem of the site was the lack of content - by recording a UI introduction screencast and integrating Adam's talk into the site. I did take a real action that moved us forward. I am sure you can surprise us.

**Comment by tboerger** [comment]
First of all you totally ignore our commitment that pull requests are simply blocked if somebody gives a -1, an exception is if too many people say the change is correct, which is not the case with 2 other votes.

Now let's get to the next parts, Jekyll have been in a totally working state and you removed it just because you think there is no benefit, you dropped/ignored other communication channels (e.g. Gitter chat), the content is not properly aligned on mobile or small devices, you added useless files (e.g. css, less and scss), you also just dropped the link to openhub to demonstrate the activity across all repositories, you are linking to a block post by adam with a label like `Blog` so that it should look like it's the official Crowbar blog...

Those are so many things, a pull request with all those issues should never be merged. And as this is not the first time that my concerns or arguments against some change are simply ignored I will not contribute any further change to that part.

Some argument like it have to go forward is simply no argumentation for just ignoring comments and directly merging. And the videos had been also integrated into the old website...

**Comment by sidthe** [comment]
@tboerger - I am happy to see you surprise everyone and showing how it's done better :) you will get 10 +1 from me.

**Comment by sidthe** [comment]
@tboerger, in the meantime - Gitter and Openhub are back on the site, Blog item removed as Adam already does a speech in a different part of the page. Is that better now from content PoV?

View on small devices is fine. What is bad is the weird behavior when it comes to unexpected aspect ratios. Fixing this is non-trivial at least to me. If you know how, have a look please.

**Comment by sidthe** [comment]
@MaximilianMeister, the 2 +1 rule is certainly fine. I've announced the first proposal for the site to cloud devel 1 week ago hosted inside my repo. If there was genuine interest to help and engage - there was a week to do so. As far as I am concerned - there was none. So let's be frank to ourselves and all further discussions, let's make them productive. We're not helping anyone.

**Comment by aplanas** [comment]
Basically I like it, but in my FF there are problems with the icons: http://paste.opensuse.org/98653024

**Comment by tboerger** [comment]
> Basically I like it, but in my FF there are problems with the icons: http://paste.opensuse.org/98653024

Those are exactly the issues I have been talking about with smaller resolutions.

**Comment by aspiers** [comment]
Yeah, I saw that with certain browser window sizes too.

**Comment by sidthe** [comment]
@aspiers know by any chance how to fix that? I can simply drop the icons.

**Comment by aspiers** [comment]
Not offhand but I'll try to find time to look into it.

**Comment by sidthe** [comment]
@aspiers it's allright. I fixed it. Also fixed a bunch of other things and tested it on several different resolutions with both chrome tools and hardware devices. The site shall now properly behave and the icon overlap does not happen anymore.

**Comment by aplanas** [comment]
@sidthe I still see the issue in http://sidthe.github.io/crowbar-page/ (Firefox). Or maybe is not updated yet?

**Comment by sidthe** [comment]
@aplanas it is now on production http://crowbar.github.io/
the one you pointed to is my repo where I started doing this. Now I moved to the actual crowbar one.

**Comment by aplanas** [comment]
@sidthe Oh I see! So there are not PR for the fixes? No review for the changes? I see the changes in `master`, but not in the `source` branch. Also in `master` I do not see this PR, nor many of the other PR.

Edit: I see that the PR in master are now in source. Is a bit confusing, sorry.

Edit II: Actually I think that pushing into production w/out review can be dangerous.

**Comment by sidthe** [comment]
@aplanas yeap. Because on Friday I have pushed it all from scratch - I addressed the concerns directly. PRs would be irrelevant in this case. I merged the source to master to keep them in sync.

Edit1
@aplanas - can be dangerous if it would have not been from scratch.

Long story short. I hope the functional concerns are now addressed , and I anyway hope this to be short lived with Ken eventually giving us a helping hand on the topic.

**Comment by sidthe** [comment]
@aplanas - can be dangerous if it would have not been from scratch.

Long story short. I hope the functional concerns are now addressed , and I anyway hope this to be short lived with Ken eventually giving us a helping hand on the topic.

**Comment by aplanas** [comment]
>  I addressed the concerns directly. PRs would be irrelevant in this case. 

@sidthe Uau, no. PR w/out reviews are only irrelevant in two situations: in our own personal project, or if we are super-developers that we never make mistakes.

> I merged the source to master to keep them in sync.

I joined late here, but I see the source / master branch confusing. What is the version that is published, master? If so, why we have source with more commits that master? If source is irrelevant we need to remove it, or fix master.

**Comment by sidthe** [comment]
@aplanas this is the way it was. Master is the one visible on the main page while the source is the default repo.

**Comment by aplanas** [comment]
> - can be dangerous if it would have not been from scratch.

Oh no. I understand that the review process can be perceived a constrain that slow the development process. Some times is the case, but the benefits most of the time compensate the slowness. The fix needs to be reviewed, even when are perceived as trivial. Executive decisions drive more mistakes that are easy to prevent following the review process.

> this is the way it was. Master is the one visible on the main page while the source is the default repo.

I have the feeling that this `source` was the devel branch and `master` the published one. In that case the direction of the rebase (master -> source) is wrong. Also I want to note that there is one PR (https://github.com/crowbar/crowbar.github.com/commit/97b089bce8a40380f30d1bcfa14a695233c5609e) that is not in master, so the review process was useless too.

Anyways, maybe this `source` branch is useless now and we can remove it (@aspiers, @tboerger ?) Also I really really insist to forbid the direct access to master without review.

**Comment by aplanas** [comment]
@sidthe I see properly the icons in the deployed version (FF 44) : )

**Comment by aspiers** [comment]
> @aspiers it's allright. I fixed it. Also fixed a bunch of other things and tested it on several different resolutions with both chrome tools and hardware devices. The site shall now properly behave and the icon overlap does not happen anymore.

Cool, nice work!

@aplanas I don't think there was any rebase, only a merge of `master` into `source`, which doesn't quite make sense to me, because `source` is no longer used.  I think it would be better to tag the previous `source` commit as `jekyll` in case we ever want to resurrect the Jekyll approach in the future and merge it with the new layout.  Tags are a good way of marking branches as dead whilst still retaining their history.  I will do that now.

@sidthe I agree with @aplanas about pushing though - even in the rare cases where it makes sense to circumvent the normal review process:
1. it's much nicer to submit a PR and immediately merge it, which keeps the process transparent and helps avoid confusion
2. IMHO there should _never_ be a force-push to a shared branch, because it breaks things for everyone else, and wipes potentially important history.  I don't expect this will ever happen again since this was a one-off scenario, but in the interest of sharing knowledge around git workflows, I'll go into more detail in case it's of use for future reference ...

There are a few problems with what happened here, but essentially it all boils down to the Principle of Least Surprise, e.g.
1. The history of `origin/master` has been forcibly wiped, so now I have to rely on my local reflog if I want to retrieve the history of the previous `master` branch. That's not nice because that could be garbage-collected at any moment.  If there had been commits to `origin/master` which were not in any other branch and were potentially useful in the case of any future work (e.g. a merge of the new layout with the Jekyll approach) then they are now harder to resurrect.
2. It's even harder for anyone who had extra commits on top of `master` in their _local_ repo and wanted to do anything with them.
3. There are two root commits, which is quite confusing, and I suspect can produce unexpected results from some `git` commands.

There shouldn't ever be a need for a force-push to a shared branch because even when major changes are required, it's possible to change an entire repo's contents in a single commit whose parent is the previous state of the branch.  Doing this and adhering to the PR protocol preserves the history and avoids all the above problems.

Again, in this particular scenario I'm fairly sure no serious damage was done - after all it's just a simple website :)  But in the interests of promoting good habits around collaborative workflows, I do think it's better for everyone if we never do that again :)

**Comment by aspiers** [comment]
Oh my bad - there are actually at least two or three root commits, and they were already there before @sidthe's redesign.  My local `master` commit has no parents or children.  Totally weird and horrible...

**Comment by tboerger** [comment]
@aspiers this happens if somebody takes care who doesn't know anything about the workflow. As you can see at https://github.com/crowbar/crowbar.github.com/blob/jekyll-source/Rakefile#L22-L43 the `source` branch was always the source of truth because `master` have been force-pushed with the fully generated website.

**Comment by tboerger** [comment]
But really interesting that our conventions for pull requests and reviews are totally ignored...

**Comment by aspiers** [comment]
> the source branch was always the source of truth

Yes I knew that.  I don't understand why `master` was regenerated and force-pushed every time though.  Why not just commit and push as normal?  That way you would have been able to see how things changed incrementally on `master`, as well as `source`, which would have been really useful.

**Comment by tboerger** [comment]
> Yes I knew that. I don't understand why master was regenerated and force-pushed every time though. Why not just commit and push as normal? That way you would have been able to see how things changed incrementally on master, as well as source, which would have been really useful.

How is it useful for the master? And how should that solve conflicts? Or remove auto generated files?

**Pull request merged**
