### PR TITLE
drop URLs from home page

### PR DESCRIPTION
**Pull request by aspiers**
They needlessly clutter the page.  No other software project with a decent website does this.

### CODE REVIEW

**Comment by tboerger** [comment]
:-1: for the current content. The website is already so damn empty... This makes it even worse. If we have more content with screenshots or whatever I'm fine with that.

**Comment by rsalevsky** [comment]
Same opinion, just removing makes no sense.

**Comment by tboerger** [comment]
> Same opinion, just removing makes no sense.

I mean there are still links to that, but i tried it and there is nearly nothing left on the page.

**Comment by rsalevsky** [comment]
Yes, maybe we should add a screenshot above the links that fills the gap.

**Comment by aspiers** [comment]
Well OK we can postpone this until after we add more content.  But it still needs to be done.  Including the URLs looks terrible.

And BTW I already provided some more content which is in https://etherpad.nue.suse.com/p/cloud-crowbar-website -
- Crowbar vs. opencrowbar
- [the quickstart guide based on the appliance](http://blog.adamspiers.org/2014/12/11/susecon-usb-stick-howto/)

but for some reason it was skipped in [the previous stories](https://trello.com/c/spPeD7hD) covering [the website](https://trello.com/c/DVcpR1UJ), so will need to be done in [the next story](https://trello.com/c/ADDkttaU).

**Comment by tboerger** [comment]
So as this will me done by @kwwii while he extends the website I will close this PR for now.

**Pull request closed without merging**
