### PR TITLE
Piwik as analytics engine

### PR DESCRIPTION
**Pull request by sidthe**
changed google analytics with piwik

### CODE REVIEW

**Comment by sidthe** [comment]
@toabctl @tboerger @aplanas is that allright?

**Comment by aplanas** [comment]
Basically +1 when https://github.com/sidthe/crowbar.github.com/commit/7088536d8d48a514064ab1b4daddbc714254f046 is dropped from the history (`git rebase -i HEAD^2`)

**Comment by toabctl** [comment]
@sidthe please squash the commits and use a single useful commit msg...

**Comment by sidthe** [comment]
@aplanas @toabctl rebased

**Comment by aplanas** [comment]
+1

**Comment by toabctl** [comment]
+1 (assuming it works)

**Comment by sidthe** [comment]
@toabctl infra guys promised it shall :) we'll see now

**Comment by sidthe** [comment]
ok, went online and it works. I have requested for a team account - so if anyone is interested, ping for credentials

**Pull request merged**
