### PR TITLE
Piwik as analytics engine

### PR DESCRIPTION
**Pull request by aplanas**

### CODE REVIEW

**Comment by aplanas** [comment]
I hope that this is OK : )

**Comment by sidthe** [comment]
thanks @aplanas 
the previous one was also ok :) But the revert seems to be less about common sense.

edit 1: @aplanas just saw you put it at the end of the body. Again, traditional, but not necessarily according to the documentation. I am not sure I understand why?

**Comment by sidthe** [comment]
@aplanas anyway - to avoid more unnecessary debate on a problem that does not even exist, please merge it your way

**Comment by aplanas** [comment]
The beginning / end of the body section is interesting. If you put that at the beginning, PIWIK will count partial HTTP 200 fragments as valid, if we put it at the end, only full 200 are counted.

Any review for this?

**Comment by sidthe** [comment]
considering the crowbar page, from what I saw during today - is far from the most popular resource on the internet, i think it truly does not matter right now. I would put it at the beginning, but that would not give us more visitors anyway. I think, instead of the useless debates people have put in this several pull requests, this time could have been taken to go and really do content for the page.

**Comment by aspiers** [comment]
+1 for this PR, in case my :+1: at the top isn't obvious.

**Comment by sidthe** [comment]
since I see 2 +1s, I think we can get back to merging it and analyzing the traffic.

**Pull request merged**
